=== michelpaliz/LM/LM/LM/TemaXML/UD4 - Ejemplos - XSD-20220223/productos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="productos">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="producto" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="producto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="codigo" type="Tlongitud" />
                <xs:element name="categoria" type="Tcat" />
                <xs:element name="iva" type="xs:integer" />
                <xs:element name="precio" type="Tdecimal" />
                <xs:element name="descuento" type="Tdescuento" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="Tdescuento">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="10" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Tlongitudentre">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="4" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Tdecimal">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="4" />
            <xs:fractionDigits value="2" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Tcat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A" />
            <xs:enumeration value="B" />
            <xs:enumeration value="C" />
            <xs:enumeration value="D" />
            <xs:enumeration value="E" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Tlongitud">
        <xs:restriction base="xs:string">
            <xs:length value="4" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== michelpaliz/LM/LM/LM/TemaXML/UD4 - Ejemplos - XSD-20220223/productos.xml
<?xml version="1.0" encoding="UTF-8"?>
<productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="productos.xsd">
    <producto>
        <nombre>Teclado</nombre>
        <codigo>C001</codigo>
        <categoria>A</categoria>
        <iva>21</iva>
        <precio>15</precio>
        <descuento>10</descuento>
    </producto>
    <producto>
        <nombre>Monitor</nombre>
        <codigo>C002</codigo>
        <categoria>B</categoria>
        <iva>21</iva>
        <precio>147.2</precio>
        <descuento>9</descuento>
    </producto>
</productos>
