=== michelpaliz/LM/LM/LM/TemaXML/Examen/ExamenTipoA/torneo.dtd
<!ELEMENT torneo (jueces?, jugadores?, partidos?)>
<!ATTLIST torneo
            nombre NMTOKENS #REQUIRED
            anyo NMTOKEN #REQUIRED
            modalidad NMTOKENS #REQUIRED>
<!ELEMENT jueces (juez)*>
<!ELEMENT juez (#PCDATA)>
<!ATTLIST juez 
            codigo ID #REQUIRED
            nacionalidad NMTOKEN #REQUIRED>
<!ELEMENT jugadores (jugador)*>
<!ELEMENT jugador (#PCDATA)>
<!ATTLIST jugador codigo ID #REQUIRED>
<!ELEMENT partidos (partido)*>
<!ELEMENT partido (resultado?)>
<!ATTLIST partido
            ronda NMTOKENS #REQUIRED
            fecha CDATA #IMPLIED
            componentes IDREFS #REQUIRED>
<!ELEMENT resultado (#PCDATA)>

=== michelpaliz/LM/LM/TemaXML/Examen/ExamenTipoA/torneo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE torneo SYSTEM "torneo.dtd">
<torneo nombre="Roland Garros" anyo="2021" modalidad="Individual Masculino">
    <jueces>
        <juez codigo="ML" nacionalidad="Suecia">Mohamed Lahyani</juez>
        <juez codigo="CR" nacionalidad="Portugal">Carlos Ramos</juez>
    </jueces>
    <jugadores>
        <jugador codigo="ND">Novak Djokovic</jugador>
        <jugador codigo="ST">Stefanos Tsitsipas</jugador>
        <jugador codigo="AZ">Alexander Zverev</jugador>
        <jugador codigo="RN">Rafael Nadal</jugador>
    </jugadores>
    <partidos>
        <partido ronda="Semifinales" fecha="11/06/2021" componentes="ST AZ ML">
            <resultado>6-3, 6-3, 4-6, 4-6, 6-3</resultado>
        </partido>
        <partido ronda="Semifinales" fecha="11/06/2021" componentes="ND RN CR">
            <resultado>3-6, 6-3, 7-6(7-4), 6-2</resultado>
        </partido>
        <partido ronda="Final" fecha="13/06/2021" componentes="ND ST ML">
            <resultado>6-7(6-8), 2-6, 6-3, 6-2, 6-4</resultado>
        </partido>
    </partidos>
</torneo>
