=== michelpaliz/LM/LM/LM/TemaXSL/Persona/persona.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre,apellido,edad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT edad (#PCDATA)>

=== michelpaliz/LM/LM/TemaXSL/Paliz_Michael_ExamenT3/Persona/persona.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="persona.xsl" type="text/xsl"?>
<?xml-model href="persona.dtd" type="application/xml-dtd"?>

<!DOCTYPE persona SYSTEM "persona.dtd">
<personas>
    <persona>
        <nombre>Michael</nombre>
        <apellido>Paliz</apellido>
        <edad>21</edad>
    </persona>
    <persona>
        <nombre>Juan</nombre>
        <apellido>Sanchez</apellido>
        <edad>25</edad>
    </persona>


</personas>
