=== michelpaliz/LM/LM/TemaXML/Ejercicios/Ejercicio2/marketplace.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="marketplace">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empresa" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="razonSocial" type="razonSocial" />
                            <xs:element name="CIF" type="cif" />
                            <xs:element name="telefono" type="telefono" minOccurs="1" maxOccurs="2" />
                            <xs:element name="datosDomicilio">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="direccion" type="textoCorto" />
                                        <xs:element name="poblacion" type="textoCorto" />
                                        <xs:element name="provincia" type="textoCorto" />
                                        <xs:element name="pais" type="textoCorto" />
                                        <xs:element name="codigoPostal" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="cliente" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="textoCorto" />
                                        <xs:element name="apellidos" type="textoCorto" />
                                        <xs:element name="DNI" type="dni" />
                                        <xs:element name="telefono" type="telefono" minOccurs="1" maxOccurs="2" />
                                        <xs:element name="datosFacturacion">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="direccion" type="textoCorto" />
                                                    <xs:element name="poblacion" type="textoCorto" />
                                                    <xs:element name="provincia" type="textoCorto" />
                                                    <xs:element name="pais" type="textoCorto" />
                                                    <xs:element name="codigoPostal" type="textoCorto" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="pedido" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="fecha" type="fecha" />
                                                    <xs:element name="descripcion" type="descripcion" />
                                                    <xs:element name="datosDomicilioEnvio" type="textoCorto" />
                                                </xs:sequence>
                                                <xs:attribute name="idPedido" type="id" use="required" />
                                                <xs:attribute name="estado" type="tipoEstado" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="clienteID" type="id" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="id" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <!-- Creacion de Elmentos Simples -->
    <xs:simpleType name="razonSocial">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Sociedad Limitada"></xs:enumeration>
            <xs:enumeration value="Sociedad Anonima"></xs:enumeration>
            <xs:enumeration value="Sociedad Colectiva"></xs:enumeration>
            <xs:enumeration value="Sociedad de Bienes"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dni">
        <xs:restriction base="xs:token">
            <xs:pattern value="[0-9]{8}[A-Z]{1}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cif">
        <xs:restriction base="xs:token">
            <xs:pattern value="[A-Z]{1}[0-9]{8}" />
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="textoCorto">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="30" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="descripcion">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="50" />
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="tipoEstado">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Entregrado"></xs:enumeration>
            <xs:enumeration value="En proceso"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="id">
        <xs:restriction base="xs:string">
            <xs:minLength value="5" />
            <xs:maxLength value="5" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fecha">
        <xs:restriction base="xs:date">
            <xs:minInclusive value="2022-01-01" />
            <xs:maxInclusive value="2022-12-31" />
            <xs:pattern value=".{10}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="telefono">
        <xs:restriction base="xs:token">
            <xs:pattern value="[0-9]{9}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== michelpaliz/LM/LM/TemaXML/Ejercicios/Ejercicio2/marketplace.xml
<?xml version="1.0" encoding="UTF-8"?>

<marketplace xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="marketplace.xsd">

    <empresa id="11111">
        <razonSocial>Sociedad Limitada</razonSocial>
        <CIF>B16841652</CIF>
        <telefono>654681542</telefono>
        <datosDomicilio>
            <direccion>Calle Senija</direccion>
            <poblacion>Denia</poblacion>
            <provincia>Alicante</provincia>
            <pais>España</pais>
            <codigoPostal>03700</codigoPostal>
        </datosDomicilio>
        <cliente clienteID="11111">
            <nombre>Michael</nombre>
            <apellidos>Paliz</apellidos>
            <DNI>53944920F</DNI>
            <telefono>654681542</telefono>
            <datosFacturacion>
                <direccion>Calle campos</direccion>
                <poblacion>Denia</poblacion>
                <provincia>Alicante</provincia>
                <pais>España</pais>
                <codigoPostal>03700</codigoPostal>
            </datosFacturacion>
            <pedido idPedido="11111" estado="En proceso">
                <fecha>2022-06-02</fecha>
                <descripcion>Zapatos nike</descripcion>
                <datosDomicilioEnvio>Calle campos</datosDomicilioEnvio>
            </pedido>


        </cliente>

        <cliente clienteID="11111">
            <nombre>Michael</nombre>
            <apellidos>Paliz</apellidos>
            <DNI>53944920F</DNI>
            <telefono>654681542</telefono>
            <datosFacturacion>
                <direccion>Calle campos</direccion>
                <poblacion>Denia</poblacion>
                <provincia>Alicante</provincia>
                <pais>España</pais>
                <codigoPostal>03700</codigoPostal>
            </datosFacturacion>
            <pedido idPedido="11111" estado="En proceso">
                <fecha>2022-06-02</fecha>
                <descripcion>Zapatos nike</descripcion>
                <datosDomicilioEnvio>Calle campos</datosDomicilioEnvio>
            </pedido>


        </cliente>

    </empresa>


    <empresa id="11111">
        <razonSocial>Sociedad Limitada</razonSocial>
        <CIF>B16841652</CIF>
        <telefono>654681542</telefono>
        <datosDomicilio>
            <direccion>Calle Senija</direccion>
            <poblacion>Denia</poblacion>
            <provincia>Alicante</provincia>
            <pais>España</pais>
            <codigoPostal>03700</codigoPostal>
        </datosDomicilio>
        <cliente clienteID="11111">
            <nombre>Michael</nombre>
            <apellidos>Paliz</apellidos>
            <DNI>53944920F</DNI>
            <telefono>654681542</telefono>
            <datosFacturacion>
                <direccion>Calle campos</direccion>
                <poblacion>Denia</poblacion>
                <provincia>Alicante</provincia>
                <pais>España</pais>
                <codigoPostal>03700</codigoPostal>
            </datosFacturacion>
            <pedido idPedido="11111" estado="En proceso">
                <fecha>2022-06-02</fecha>
                <descripcion>Zapatos nike</descripcion>
                <datosDomicilioEnvio>Calle campos</datosDomicilioEnvio>
            </pedido>
            <pedido idPedido="11111" estado="En proceso">
                <fecha>2022-06-02</fecha>
                <descripcion>Zapatos nike</descripcion>
                <datosDomicilioEnvio>Calle campos</datosDomicilioEnvio>
            </pedido>
            <pedido idPedido="11111" estado="En proceso">
                <fecha>2022-06-02</fecha>
                <descripcion>Zapatos nike</descripcion>
                <datosDomicilioEnvio>Calle campos</datosDomicilioEnvio>
            </pedido>


        </cliente>

        <cliente clienteID="11111">
            <nombre>Michael</nombre>
            <apellidos>Paliz</apellidos>
            <DNI>53944920F</DNI>
            <telefono>654681542</telefono>
            <datosFacturacion>
                <direccion>Calle campos</direccion>
                <poblacion>Denia</poblacion>
                <provincia>Alicante</provincia>
                <pais>España</pais>
                <codigoPostal>03700</codigoPostal>
            </datosFacturacion>
            <pedido idPedido="11111" estado="En proceso">
                <fecha>2022-06-02</fecha>
                <descripcion>Zapatos nike</descripcion>
                <datosDomicilioEnvio>Calle campos</datosDomicilioEnvio>
            </pedido>


        </cliente>


    </empresa>

</marketplace>
