=== michelpaliz/LM/LM/LM/TemaXML/UD4 - Actividades- corregidos/ordenadores1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ordenadores">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ordenador" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <!-- Mismo ejemplo que ordenadores.xsd sin definición de tipo simple -->
                            <xs:element name="tipo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Sobremesa" />
                                        <xs:enumeration value="Portátil" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fabricacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="inicio" type="xs:date" />
                                        <xs:element name="fin" type="xs:date" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="modificaciones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="modificacion" maxOccurs="unbounded" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== michelpaliz/LM/LM/LM/TemaXML/Ejercicios/Ejercicio1/ordenadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<ordenadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ordenadores1.xsd">
    <!-- HOLA -->
    <!-- HOLA -->
    <!-- HOLA -->
    <ordenador>
        <nombre>PC Gaming</nombre>
        <tipo>Sobremesa</tipo>
        <fabricacion>
            <inicio>01/01/2022</inicio>
            <fin>15/02/2022</fin>
        </fabricacion>
        <modificaciones>
            <modificacion>Ampliaci√≥n memoria RAM</modificacion>
            <modificacion>Cambio placa base</modificacion>
        </modificaciones>
    </ordenador>
</ordenadores>
