=== michelpaliz/LM/ExamenLM/Ejercicio1/torneoXSD.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="torneo">
        <xs:complexType>
            <!-- !ROOT = TORNEO(JUECES, JUGADORES,PARTIDO) -->
            <xs:sequence>
                <xs:element name="jueces">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="juez" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="codigo" use="required" />
                                            <xs:attribute name="nacionalidad" use="required" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="jugadores">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="jugador" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="codigo" use="required" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="partidos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="partido" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="resultado">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="set" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="numero" type="xs:integer" use="required" />
                                                                    <xs:attribute name="tiebreak" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="ronda" use="required" />
                                    <xs:attribute name="fecha" use="required" />
                                    <xs:attribute name="jugadores" use="required" />
                                    <xs:attribute name="juez" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nombre" use="required" />
            <xs:attribute name="anyo" type="xs:integer" use="required" />
            <xs:attribute name="modalidad" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="partido">
        <xs:sequence>
            <xs:element name="cuartos_de_final" type="xs:string" />
            <xs:element name="Semifinales" type="xs:string" />
            <xs:element name="Final" type="xs:string" />
        </xs:sequence>
    </xs:complexType>


</xs:schema>

=== michelpaliz/LM/ExamenLM/Ejercicio1/torneoDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-model href="TorneoDTD.dtd" type="application/xml-dtd"?> -->
<torneo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="torneoXSD.xsd"
 nombre="Roland Garros" anyo="2021" modalidad="Individual Masculino">
    <jueces>
        <juez codigo="ML" nacionalidad="Suecia">Mohamed Lahyani</juez>
        <juez codigo="CR" nacionalidad="Portugal">Carlos Ramos</juez>
    </jueces>
    <jugadores>
        <jugador codigo="ND">Novak Djokovic</jugador>
        <jugador codigo="ST">Stefanos Tsitsipas</jugador>
        <jugador codigo="AZ">Alexander Zverev</jugador>
        <jugador codigo="RN">Rafael Nadal</jugador>
    </jugadores>
    <partidos>
        <partido ronda="Semifinales" fecha="11/06/2021" jugadores="ST AZ" juez="ML">
            <resultado>
                <set numero="1">6-3</set>
                <set numero="2">6-3</set>
                <set numero="3">4-6</set>
                <set numero="4">4-6</set>
                <set numero="5">6-3</set>
            </resultado>
        </partido>
        <partido ronda="Semifinales" fecha="11/06/2021" jugadores="ND RN" juez="CR">
            <resultado>
                <set numero="1">3-6</set>
                <set numero="2">6-3</set>
                <set numero="3" tiebreak="si">7-6 (7-4)</set>
                <set numero="4">6-2</set>
            </resultado>
        </partido>
        <partido ronda="Final" fecha="13/06/2021" jugadores="ND ST" juez="ML">
            <resultado>
                <set numero="1" tiebreak="si">6-7 (6-8)</set>
                <set numero="2">2-6</set>
                <set numero="3">6-3</set>
                <set numero="4">6-2</set>
                <set numero="5">6-4</set>
            </resultado>
        </partido>
    </partidos>
</torneo>

=== michelpaliz/LM/LM/LM/TemaXML/Examen/ExamenTipoB/torneoXSD (1).xml
<?xml version="1.0" encoding="UTF-8"?>
<torneo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="torneoXSD.xsd" nombre="Roland Garros" anyo="2021" modalidad="Individual Masculino">
    <partidos>
        <partido ronda="Semifinales" fecha="2021-06-11">
            <resultado>
                <set numero="1">6-3</set>
                <set numero="2">6-3</set>
                <set numero="3">4-6</set>
                <set numero="4">4-6</set>
                <set numero="5">6-3</set>
            </resultado>
        </partido>
        <partido ronda="Semifinales" fecha="2021-06-11">
            <resultado>
                <set numero="1">3-6</set>
                <set numero="2">6-3</set>
                <set numero="3" tiebreak="si">7-6 (7-4)</set>
                <set numero="4">6-2</set>
            </resultado>
        </partido>
        <partido ronda="Final" fecha="2021-06-13">
            <resultado>
                <set numero="1" tiebreak="si">6-7 (6-8)</set>
                <set numero="2">2-6</set>
                <set numero="3">6-3</set>
                <set numero="4">6-2</set>
                <set numero="5">6-4</set>
            </resultado>
        </partido>
    </partidos>
</torneo>
